const racing = [
    {
       marka:"kawasaki",
       model:"zx6r",
       yil:"2023",
       tip:"racing",
       img:"./zx6r.png"
    },
    {
        marka:"kawasaki",
        model:"zx4rr",
        yil:"2023",
        tip:"racing",
        img:"./zx4rrpng.png"
     },
     {
        marka:"kawasaki",
        model:"zx10r",
        yil:"2022",
        tip:"racing",
        img:"./zx10r.png"
     },
     {
        marka:"kawasaki",
        model:"ninja400",
        yil:"2020",
        tip:"racing",
        img:"./ninja400png.png"
     },
     {
        marka:"Honda",
        model:"cbr600rr",
        yil:"2015",
        tip:"racing",
        img:"./cbr600rr.png"
     },
     {
        marka:"Honda",
        model:"cbr1000rrr",
        yil:"2022",
        tip:"racing",
        img:"./cbr1000rrr.jpg"
     },
     {
        marka:"Yamaha",
        model:"r25",
        yil:"2022",
        tip:"racing",
        img:"./r25.jpg"
     },
     {
        marka:"Yamaha",
        model:"r6",
        yil:"2022",
        tip:"racing",
        img:"./r6.jpg"
     },
     {
        marka:"Yamaha",
        model:"r1",
        yil:"2022",
        tip:"racing",
        img:"./r1.jpg"
     },
     {
        marka:"Suzuki",
        model:"gsxr250",
        yil:"2022",
        tip:"racing",
        img:"./gsxr250.jpg"
     },
     {
        marka:"Suzuki",
        model:"gsxr600",
        yil:"2022",
        tip:"racing",
        img:"./gsxr600.jpg"
     },
     {
        marka:"Suzuki",
        model:"gsxr1000",
        yil:"2022",
        tip:"racing",
        img:"./gsxr1000.jpg"
     },
]